version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
#      - ../certbot/conf:/etc/letsencrypt
#      - ../certbot/www:/var/www/certbot
    ports:
      - 80:80
#      - 443:443
#    expose:
#      - 80
#      - 443
#    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

#  certbot:
#    image: certbot/certbot
#    container_name: certbot_service
#    volumes:
#      - ../certbot/conf:/etc/letsencrypt
#      - ../certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  django_container_gunicorn:
    image: django_jb_cf:7
    networks:
    - network
    volumes:
      - static-volume:/home/pragmatic/staticfiles
      - media-volume:/home/pragmatic/media

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: password1234

networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database: